"""Update ProductMovement Updated column names

Revision ID: 65204ef946f3
Revises: ce2f1bdc8900
Create Date: 2025-12-07 02:52:47.630557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65204ef946f3'
down_revision = 'ce2f1bdc8900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productmovement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('to_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'location', ['to_location_id'], ['location_id'])
        batch_op.create_foreign_key(None, 'location', ['from_location_id'], ['location_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productmovement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('to_location_id')
        batch_op.drop_column('from_location_id')

    # ### end Alembic commands ###
