"""initial tables

Revision ID: c23824a47488
Revises: 
Create Date: 2025-11-27 05:23:46.928677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23824a47488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('productmovement',
    sa.Column('movement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('from_location', sa.String(length=20), nullable=True),
    sa.Column('to_location', sa.String(length=20), nullable=True),
    sa.Column('product_id', sa.String(length=20), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_table('stock',
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('productmovement')
    op.drop_table('product')
    op.drop_table('location')
    # ### end Alembic commands ###
