"""Update ProductMovement relationships

Revision ID: ce2f1bdc8900
Revises: 3988a5e7ff2e
Create Date: 2025-12-07 02:48:38.259749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce2f1bdc8900'
down_revision = '3988a5e7ff2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productmovement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('productmovement_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('productmovement_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('from_location')
        batch_op.drop_column('to_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productmovement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_location', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('from_location', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('productmovement_ibfk_3'), 'location', ['to_location'], ['location_id'])
        batch_op.create_foreign_key(batch_op.f('productmovement_ibfk_1'), 'location', ['from_location'], ['location_id'])

    # ### end Alembic commands ###
